steps:
  # build & push the container image
- name: "gcr.io/kaniko-project/executor:latest"
  args: ["--cache=true", "--cache-ttl=48h", "--destination=gcr.io/$PROJECT_ID/$REPO_NAME:$BRANCH_NAME", "--dockerfile=Dockerfile"]
  # run test with earlier image
- name: 'gcr.io/cloud-builders/docker'
  args: ["pull", "--cache-from", "gcr.io/$PROJECT_ID/$REPO_NAME:$BRANCH_NAME"]
